[2022-10-11 09:46:59 +0800] [891384] [INFO] Starting gunicorn 20.1.0
[2022-10-11 09:46:59 +0800] [891384] [ERROR] Connection in use: ('0.0.0.0', 8187)
[2022-10-11 09:46:59 +0800] [891384] [ERROR] Retrying in 1 second.
[2022-10-11 09:47:00 +0800] [891384] [ERROR] Connection in use: ('0.0.0.0', 8187)
[2022-10-11 09:47:00 +0800] [891384] [ERROR] Retrying in 1 second.
[2022-10-11 09:47:01 +0800] [891384] [ERROR] Connection in use: ('0.0.0.0', 8187)
[2022-10-11 09:47:01 +0800] [891384] [ERROR] Retrying in 1 second.
[2022-10-11 09:47:02 +0800] [891384] [ERROR] Connection in use: ('0.0.0.0', 8187)
[2022-10-11 09:47:02 +0800] [891384] [ERROR] Retrying in 1 second.
[2022-10-11 09:47:03 +0800] [891384] [ERROR] Connection in use: ('0.0.0.0', 8187)
[2022-10-11 09:47:03 +0800] [891384] [ERROR] Retrying in 1 second.
[2022-10-11 09:47:04 +0800] [891384] [ERROR] Can't connect to ('0.0.0.0', 8187)
[2022-10-13 08:25:54 +0800] [2343060] [INFO] Starting gunicorn 20.1.0
[2022-10-13 08:25:54 +0800] [2343060] [INFO] Listening at: http://0.0.0.0:8186 (2343060)
[2022-10-13 08:25:54 +0800] [2343060] [INFO] Using worker: gevent
[2022-10-13 08:25:54 +0800] [2343062] [INFO] Booting worker with pid: 2343062
[2022-10-13 08:25:54 +0800] [2343068] [INFO] Booting worker with pid: 2343068
[2022-10-13 08:27:08,513] ERROR in app: Exception on /register/url [POST]
Traceback (most recent call last):
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lyxx/anaconda3/envs/fnet/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/mnt/zhaosheng/Voiceprint-Recognition-System-bak/test/voiceprint-recognition-system/src/server.py", line 75, in register_or_reasoning
    response = general(
  File "/mnt/zhaosheng/Voiceprint-Recognition-System-bak/test/voiceprint-recognition-system/src/utils/advanced/general.py", line 292, in general
    return register(
  File "/mnt/zhaosheng/Voiceprint-Recognition-System-bak/test/voiceprint-recognition-system/src/utils/register/register.py", line 88, in register
    add_speaker(skp_info, after_vad_length=after_vad_length)
  File "/mnt/zhaosheng/Voiceprint-Recognition-System-bak/test/voiceprint-recognition-system/src/utils/orm/query.py", line 192, in add_speaker
    cur.execute(query_sql)
  File "/home/lyxx/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/lyxx/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/lyxx/.local/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/lyxx/.local/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/lyxx/.local/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/lyxx/.local/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/lyxx/.local/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/lyxx/.local/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '15151832002' for key 'phone'")
[2022-10-13 08:38:43 +0800] [2343062] [INFO] Parent changed, shutting down: <Worker 2343062>
[2022-10-13 08:38:43 +0800] [2343062] [INFO] Worker exiting (pid: 2343062)
[2022-10-13 08:38:43 +0800] [2343068] [INFO] Parent changed, shutting down: <Worker 2343068>
[2022-10-13 08:38:43 +0800] [2343068] [INFO] Worker exiting (pid: 2343068)
[2022-10-13 09:27:24 +0800] [2488399] [INFO] Starting gunicorn 20.1.0
[2022-10-13 09:27:24 +0800] [2488399] [INFO] Listening at: http://0.0.0.0:8186 (2488399)
[2022-10-13 09:27:24 +0800] [2488399] [INFO] Using worker: gevent
[2022-10-13 09:27:24 +0800] [2488401] [INFO] Booting worker with pid: 2488401
[2022-10-13 09:27:24 +0800] [2488402] [INFO] Booting worker with pid: 2488402
[2022-10-13 09:28:19 +0800] [2488401] [INFO] Parent changed, shutting down: <Worker 2488401>
[2022-10-13 09:28:19 +0800] [2488401] [INFO] Worker exiting (pid: 2488401)
[2022-10-13 09:28:20 +0800] [2488402] [INFO] Parent changed, shutting down: <Worker 2488402>
[2022-10-13 09:28:20 +0800] [2488402] [INFO] Worker exiting (pid: 2488402)
[2022-10-26 10:22:52 +0800] [3171627] [INFO] Starting gunicorn 20.1.0
[2022-10-26 10:22:52 +0800] [3171627] [INFO] Listening at: http://0.0.0.0:8186 (3171627)
[2022-10-26 10:22:52 +0800] [3171627] [INFO] Using worker: gevent
[2022-10-26 10:22:52 +0800] [3171629] [INFO] Booting worker with pid: 3171629
[2022-10-26 10:22:52 +0800] [3171630] [INFO] Booting worker with pid: 3171630
[2022-10-26 10:25:04 +0800] [3176743] [INFO] Starting gunicorn 20.1.0
[2022-10-26 10:26:18 +0800] [3179919] [INFO] Starting gunicorn 20.1.0
[2022-10-26 10:26:18 +0800] [3179919] [INFO] Listening at: http://0.0.0.0:8186 (3179919)
[2022-10-26 10:26:18 +0800] [3179919] [INFO] Using worker: gevent
[2022-10-26 10:26:18 +0800] [3179921] [INFO] Booting worker with pid: 3179921
[2022-10-26 10:26:18 +0800] [3179922] [INFO] Booting worker with pid: 3179922
[2022-10-26 10:27:17 +0800] [3182245] [INFO] Starting gunicorn 20.1.0
[2022-10-26 10:27:17 +0800] [3182245] [INFO] Listening at: http://0.0.0.0:8186 (3182245)
[2022-10-26 10:27:17 +0800] [3182245] [INFO] Using worker: gevent
[2022-10-26 10:27:17 +0800] [3182247] [INFO] Booting worker with pid: 3182247
[2022-10-26 10:49:32 +0800] [3233130] [INFO] Starting gunicorn 20.1.0
[2022-10-26 10:49:32 +0800] [3233130] [INFO] Listening at: http://0.0.0.0:8186 (3233130)
[2022-10-26 10:49:32 +0800] [3233130] [INFO] Using worker: gevent
[2022-10-26 10:49:32 +0800] [3233135] [INFO] Booting worker with pid: 3233135
[2022-10-26 10:49:50 +0800] [3234000] [INFO] Starting gunicorn 20.1.0
[2022-10-26 10:49:50 +0800] [3234000] [INFO] Listening at: http://0.0.0.0:8186 (3234000)
[2022-10-26 10:49:50 +0800] [3234000] [INFO] Using worker: gevent
[2022-10-26 10:49:50 +0800] [3234003] [INFO] Booting worker with pid: 3234003
[2022-10-26 11:27:39 +0800] [3321886] [INFO] Starting gunicorn 20.1.0
[2022-10-26 11:27:39 +0800] [3321886] [INFO] Listening at: http://0.0.0.0:8186 (3321886)
[2022-10-26 11:27:39 +0800] [3321886] [INFO] Using worker: gevent
[2022-10-26 11:27:39 +0800] [3321888] [INFO] Booting worker with pid: 3321888
[2022-10-26 11:27:45 +0800] [3321888] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/lyxx/anaconda3/envs/fnet/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/lyxx/anaconda3/envs/fnet/lib/python3.8/site-packages/gunicorn/workers/ggevent.py", line 146, in init_process
    super().init_process()
  File "/home/lyxx/anaconda3/envs/fnet/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/lyxx/anaconda3/envs/fnet/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/lyxx/anaconda3/envs/fnet/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/lyxx/anaconda3/envs/fnet/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/lyxx/anaconda3/envs/fnet/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/lyxx/anaconda3/envs/fnet/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/home/lyxx/anaconda3/envs/fnet/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/mnt/zhaosheng/Voiceprint-Recognition-System-bak/test/voiceprint-recognition-system/src/vaf_server.py", line 14, in <module>
    from utils.advanced import general
  File "/mnt/zhaosheng/Voiceprint-Recognition-System-bak/test/voiceprint-recognition-system/src/utils/advanced/__init__.py", line 6, in <module>
    from utils.advanced.general import general
  File "/mnt/zhaosheng/Voiceprint-Recognition-System-bak/test/voiceprint-recognition-system/src/utils/advanced/general.py", line 27, in <module>
    from utils.info import OutInfo
  File "/mnt/zhaosheng/Voiceprint-Recognition-System-bak/test/voiceprint-recognition-system/src/utils/info/__init__.py", line 1, in <module>
    from out import OutInfo
ModuleNotFoundError: No module named 'out'
[2022-10-26 11:27:45 +0800] [3321888] [INFO] Worker exiting (pid: 3321888)
[2022-10-26 11:27:46 +0800] [3321886] [INFO] Shutting down: Master
[2022-10-26 11:27:46 +0800] [3321886] [INFO] Reason: Worker failed to boot.
[2022-10-26 11:29:01 +0800] [3325405] [INFO] Starting gunicorn 20.1.0
[2022-10-26 11:29:01 +0800] [3325405] [INFO] Listening at: http://0.0.0.0:8186 (3325405)
[2022-10-26 11:29:01 +0800] [3325405] [INFO] Using worker: gevent
[2022-10-26 11:29:01 +0800] [3325407] [INFO] Booting worker with pid: 3325407
